[package]
name = "{{project-name}}"
version = "0.1.0"
authors = ["{{authors}}"]
edition = "2021"
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
extism-pdk = "0.3.4"
matricks_plugin = "0.1.4"
serde_json = "1.0.107"
lazy_static = "1.4.0"